CREATE DATABASE IF NOT EXISTS BTA_DB;
USE BTA_DB;

DROP TABLE IF EXISTS SessionItem;
DROP TABLE IF EXISTS Session_Connection;
DROP TABLE IF EXISTS GlobalAchievements;
DROP TABLE IF EXISTS Item;
DROP TABLE IF EXISTS Session;
DROP TABLE IF EXISTS Player;

-- Akarunk soft delete - et?
CREATE TABLE Player (
    Epic_Account_Id VARCHAR(50) PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE Session (
    Id INTEGER PRIMARY KEY AUTO_INCREMENT,
    started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Name VARCHAR(50) NOT NULL,
    Session_Code INTEGER NOT NULL,
    SaveFile MEDIUMBLOB NOT NULL,
    LastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE Item (
    Id INTEGER PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Rarity VARCHAR(50) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE Session_Connection (
    Id INTEGER PRIMARY KEY AUTO_INCREMENT,
    Player_Epic_Account_Id VARCHAR(50),
    Session_Id INTEGER, 
    Character_Id INTEGER NOT NULL,
    FOREIGN KEY (Player_Epic_Account_Id) REFERENCES Player(Epic_Account_Id) ON DELETE CASCADE,
    FOREIGN KEY (Session_Id) REFERENCES Session(Id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE SessionItem (
    Id INTEGER PRIMARY KEY AUTO_INCREMENT,
    Session_Id INTEGER, 
    Item_Id INTEGER,
    Amount INTEGER NOT NULL,
    FOREIGN KEY (Session_Id) REFERENCES Session(Id) ON DELETE CASCADE,
    FOREIGN KEY (Item_Id) REFERENCES Item(Id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE GlobalAchievements (
    Id INTEGER PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Description VARCHAR(255) NOT NULL,
    Current_Value INTEGER NOT NULL DEFAULT 0,
    Target_Value INTEGER NOT NULL,
    Rewards VARCHAR(255) NOT NULL, -- Itt tárolhatunk JSON stringet is
    Achieved_At TIMESTAMP NULL DEFAULT NULL,
    Notes VARCHAR(255)
) ENGINE=InnoDB;