// Copyright 2024 Arkai Interactive. All Rights Reserved.

#pragma once
#include "CoreMinimal.h"
#include "AssetTypeCategories.h"
#include "Modules/ModuleInterface.h"
#include "Factories/Factory.h"
#include "Modules/ModuleManager.h"
#include "Kismet2/KismetEditorUtilities.h"
#include "Styling/SlateStyle.h"
#include "Modules/ModuleManager.h"




DECLARE_LOG_CATEGORY_EXTERN(LogInventory, Log, All);

#define RegisterDefaultEvent(Class, FuncName) \
(FKismetEditorUtilities::RegisterAutoGeneratedDefaultEvent(this, Class::StaticClass(), GET_FUNCTION_NAME_CHECKED(Class, FuncName)))



class FChestoryEditor : public IModuleInterface
{
public:

	TSharedPtr<FSlateStyleSet> StyleSet;
	EAssetTypeCategories::Type ChestoryAssetCategory;

	/** IModuleInterface implementation */
	virtual void StartupModule() override;
	virtual void ShutdownModule() override;



	// -----------Auto AssetManager add Rule
	
	static const FPrimaryAssetType	ItemDataType;

	// Check if found ItemDataAsset setting in AssetManager
	bool CheskHasSetting();

	// If it not found ItemDataAsset in AssetManager try to add a new Rule
	void AddRuleInAssetManager();
};
